apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  generateName: crossplane-bucket-for-testing-purpose-only-hehe
  name: crossplane-bucket-for-testing-purpose-only-hehe
  labels:
    docs.crossplane.io/example: provider-gcp
spec:
  forProvider:
    location: EU
    storageClass: MULTI_REGIONAL
  providerConfigRef:
    name: default
  deletionPolicy: Delete
